// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/create-text-share.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { z } from "npm:zod@^4.4.3";
var CHARS = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
function generateCode() {
  let c = "";
  for (let i = 0; i < 6; i++) c += CHARS[Math.floor(Math.random() * CHARS.length)];
  return c;
}
var create_text_share_default = defineTool({
  name: "create_text_share",
  title: "Create text share",
  description: "Create an ephemeral text share on DropZone. Returns a 6-character room code that anyone can use to retrieve the text before it expires.",
  inputSchema: {
    text: z.string().min(1).describe("The text content to share."),
    expiryMinutes: z.number().int().min(1).max(1440).optional().describe("Minutes until the share expires. Defaults to 15.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ text, expiryMinutes }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const code = generateCode();
    const minutes = expiryMinutes ?? 15;
    const expiresAt = new Date(Date.now() + minutes * 6e4).toISOString();
    const { error } = await supabase.from("shared_items").insert({
      code,
      type: "text",
      content: text,
      encrypted: false,
      expires_at: expiresAt
    });
    if (error) {
      return { content: [{ type: "text", text: `Failed to create share: ${error.message}` }], isError: true };
    }
    return {
      content: [
        { type: "text", text: `Room code: ${code} (expires in ${minutes} minutes)` }
      ],
      structuredContent: { roomCode: code, expiresAt, expiresInMinutes: minutes }
    };
  }
});

// src/lib/mcp/tools/retrieve-share.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
import { z as z2 } from "npm:zod@^4.4.3";
var retrieve_share_default = defineTool2({
  name: "retrieve_share",
  title: "Retrieve share",
  description: "Retrieve a DropZone share by its 6-character room code. Returns the shared text, or metadata for files and encrypted shares.",
  inputSchema: {
    roomCode: z2.string().min(6).max(6).describe("The 6-character room code.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ roomCode }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data: rows, error } = await supabase.rpc("get_shared_item", {
      _code: roomCode.toUpperCase()
    });
    if (error) {
      return { content: [{ type: "text", text: `Lookup failed: ${error.message}` }], isError: true };
    }
    const data = Array.isArray(rows) ? rows[0] : null;
    if (!data) {
      return { content: [{ type: "text", text: "Not found or expired." }], isError: true };
    }
    if (data.encrypted) {
      return {
        content: [
          { type: "text", text: `Share ${data.code} is end-to-end encrypted. Retrieve it in the DropZone app using the full token that includes the decryption key.` }
        ],
        structuredContent: {
          roomCode: data.code,
          type: data.type,
          encrypted: true,
          fileName: data.file_name,
          expiresAt: data.expires_at
        }
      };
    }
    if (data.type === "file") {
      return {
        content: [
          { type: "text", text: `File share "${data.file_name}" (${data.file_type ?? "unknown type"}). Download it in the DropZone app.` }
        ],
        structuredContent: {
          roomCode: data.code,
          type: "file",
          fileName: data.file_name,
          fileType: data.file_type,
          expiresAt: data.expires_at
        }
      };
    }
    return {
      content: [{ type: "text", text: data.content }],
      structuredContent: {
        roomCode: data.code,
        type: "text",
        text: data.content,
        expiresAt: data.expires_at
      }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dropzone-mcp",
  title: "DropZone MCP",
  version: "0.1.0",
  instructions: "DropZone is an ephemeral text/file sharing service. Use `create_text_share` to store a short text snippet and receive a 6-character room code, and `retrieve_share` to fetch a share by its room code. Encrypted shares require the full token from the DropZone app.",
  tools: [create_text_share_default, retrieve_share_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
